from typing import Any, Literal, TypedDict

import psycopg2
import psycopg2.extras
from supabase import Client

from app.core.types import Mode


class Message(TypedDict):
    content: str
    role: Literal['user', 'assistant']
    timestamp: str | None


class ConversationResult(TypedDict):
    messages: list[Message]
    summary: str | None
    summarized_at: str | None
    course: str
    mode: Mode | None


class ConversationUpdateResult(TypedDict):
    userMessage: str
    aiMessage: str
    mode: Mode


class Database:
    client: Client | None
    database_url: str

    def __init__(self, client: Client | None = None, database_url: str = ""):
        self.client = client
        self.database_url = database_url
        if self.database_url:
            self._initialize_local_db()
        elif self.client is None:
            raise ValueError("Database requires either a Supabase client or DATABASE_URL")

    def _connect(self):
        conn = psycopg2.connect(self.database_url)
        conn.set_client_encoding("UTF8")
        return conn

    def _execute_one(self, sql: str, params: tuple[Any, ...] = ()):
        with self._connect() as conn:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cursor:
                cursor.execute(sql, params)
                return cursor.fetchone()

    def _execute_all(self, sql: str, params: tuple[Any, ...] = ()):
        with self._connect() as conn:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cursor:
                cursor.execute(sql, params)
                return cursor.fetchall()

    def _execute(self, sql: str, params: tuple[Any, ...] = ()):
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(sql, params)

    def _initialize_local_db(self):
        self._execute(
            """
            SELECT pg_advisory_xact_lock(hashtext('mathchat_schema_init'));

            CREATE TABLE IF NOT EXISTS courses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code TEXT UNIQUE NOT NULL
            );

            CREATE TABLE IF NOT EXISTS modes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT UNIQUE NOT NULL
            );

            CREATE TABLE IF NOT EXISTS conversations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
                summary TEXT,
                title TEXT,
                created_at TIMESTAMPTZ DEFAULT now(),
                course_id BIGINT REFERENCES courses(id),
                mode_id BIGINT REFERENCES modes(id),
                user_id UUID,
                summarized_at TIMESTAMPTZ
            );

            CREATE TABLE IF NOT EXISTS messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                timestamp TIMESTAMPTZ DEFAULT now() NOT NULL
            );

            INSERT INTO courses (id, code)
            VALUES (1, 'MATH 203')
            ON CONFLICT (id) DO NOTHING;

            INSERT INTO modes (id, name)
            VALUES (1, 'Concept'), (2, 'Problem'), (3, 'Other')
            ON CONFLICT (id) DO NOTHING;
            """
        )

    def _getMode(self, mode_id: int | None):
        if not mode_id:
            return None
        if self.database_url:
            row = self._execute_one("SELECT name FROM modes WHERE id = %s", (mode_id,))
            return row["name"] if row else None

        assert self.client
        response = (
            self.client
            .table("modes")
            .select("name")
            .eq("id", mode_id)
            .single()
            .execute()
        )
        return response.data["name"]

    def _getModeId(self, conversation_type: str):
        if self.database_url:
            row = self._execute_one("SELECT id FROM modes WHERE name = %s", (conversation_type,))
            if not row:
                raise ValueError(f"Mode not found: {conversation_type}")
            return row["id"]

        assert self.client
        response = (
            self.client
            .table("modes")
            .select("id")
            .eq("name", conversation_type)
            .single()
            .execute()
        )
        return response.data["id"]

    def _getCourse(self, course_id: int):
        if self.database_url:
            row = self._execute_one("SELECT code FROM courses WHERE id = %s", (course_id,))
            if not row:
                raise ValueError(f"Course not found: {course_id}")
            return row["code"]

        assert self.client
        response = (
            self.client
            .table("courses")
            .select("code")
            .eq("id", course_id)
            .single()
            .execute()
        )
        return response.data["code"]

    def _getCourseId(self, course: str) -> int:
        if self.database_url:
            row = self._execute_one("SELECT id FROM courses WHERE code = %s", (course,))
            if not row:
                raise ValueError(f"Course not found: {course}")
            return row["id"]

        assert self.client
        response = (
            self.client
            .table("courses")
            .select("id")
            .eq("code", course)
            .single()
            .execute()
        )
        return response.data["id"]

    def _getMessages(self, conversation_id: int, timestamp: str | None) -> list[Message]:
        if self.database_url:
            if timestamp:
                data = self._execute_all(
                    """
                    SELECT content, role, timestamp
                    FROM messages
                    WHERE conversation_id = %s AND timestamp > %s
                    ORDER BY timestamp ASC
                    """,
                    (conversation_id, timestamp),
                )
            else:
                data = self._execute_all(
                    """
                    SELECT content, role, timestamp
                    FROM messages
                    WHERE conversation_id = %s
                    ORDER BY timestamp ASC
                    """,
                    (conversation_id,),
                )
        else:
            assert self.client
            query = self.client.table("messages").select()
            if timestamp:
                query = query.gt("timestamp", timestamp)
            response = (
                query
                .order("timestamp", desc=False)
                .eq("conversation_id", conversation_id)
                .execute()
            )
            data = response.data

        messages: list[Message] = []
        for raw_message in data:
            messages.append({
                'content': raw_message['content'],
                'role': raw_message['role'],
                'timestamp': str(raw_message['timestamp']) if raw_message['timestamp'] else None
            })
        return messages

    def GetConversation(self, user_id: str | None, conversation_id: int) -> ConversationResult:
        if self.database_url:
            if user_id is None:
                settings = self._execute_one(
                    "SELECT * FROM conversations WHERE id = %s AND user_id IS NULL",
                    (conversation_id,),
                )
            else:
                settings = self._execute_one(
                    "SELECT * FROM conversations WHERE id = %s AND user_id = %s",
                    (conversation_id, user_id),
                )
        else:
            assert self.client
            query = (
                self.client
                .table("conversations")
                .select()
                .eq("id", conversation_id)
            )
            if user_id is None:
                query = query.is_("user_id", "null")
            else:
                query = query.eq("user_id", user_id)
            settings = query.single().execute().data

        if not settings:
            raise ValueError(f"Conversation not found: {conversation_id}")

        timestamp = None
        if settings["summary"] and settings["summarized_at"]:
            timestamp = str(settings["summarized_at"])

        return {
            'messages': self._getMessages(conversation_id, timestamp),
            'summary': settings["summary"],
            'mode': self._getMode(settings["mode_id"]),
            'course': self._getCourse(settings["course_id"]),
            'summarized_at': str(settings["summarized_at"]) if settings["summarized_at"] else None
        }

    def GetConversations(self, user_id: str | None, start: int, end: int):
        if self.database_url:
            limit = end - start + 1
            if user_id is None:
                return self._execute_all(
                    """
                    SELECT *
                    FROM conversations
                    WHERE user_id IS NULL
                    ORDER BY created_at DESC
                    LIMIT %s OFFSET %s
                    """,
                    (limit, start),
                )
            return self._execute_all(
                """
                SELECT *
                FROM conversations
                WHERE user_id = %s
                ORDER BY created_at DESC
                LIMIT %s OFFSET %s
                """,
                (user_id, limit, start),
            )

        assert self.client
        query = (
            self.client
                .table("conversations")
                .select()
                .range(start, end)
                .order("created_at", desc=True)
        )
        if user_id is None:
            query = query.is_("user_id", "null")
        else:
            query = query.eq("user_id", user_id)
        return query.execute().data

    def _addMessage(self, conversation_id: int, role: str, content: str):
        if self.database_url:
            self._execute(
                """
                INSERT INTO messages (conversation_id, role, content)
                VALUES (%s, %s, %s)
                """,
                (conversation_id, role, content),
            )
            return

        assert self.client
        _ = (
            self.client
            .table("messages")
            .insert({
                "conversation_id": conversation_id,
                "role": role,
                "content": content,
                })
            .execute()
        )

    def AddConversation(self, user_id: str | None, course: str) -> int:
        course_id = self._getCourseId(course)
        if self.database_url:
            row = self._execute_one(
                """
                INSERT INTO conversations (course_id, user_id)
                VALUES (%s, %s)
                RETURNING id
                """,
                (course_id, user_id),
            )
            return row["id"]

        assert self.client
        response = (
            self.client
            .table("conversations")
            .insert({
                "course_id": course_id,
                "user_id": user_id,
                })
            .execute()
        )
        return response.data[0]["id"]

    def UpdateConversation(self, conversation_id: int, request: ConversationUpdateResult):
        self._addMessage(conversation_id, 'user', request["userMessage"])
        self._addMessage(conversation_id, 'assistant', request["aiMessage"])
        mode_id = self._getModeId(request["mode"].value)
        if self.database_url:
            self._execute(
                """
                UPDATE conversations
                SET mode_id = %s, updated_at = now()
                WHERE id = %s
                """,
                (mode_id, conversation_id),
            )
            return

        assert self.client
        _ = (
            self.client
            .table("conversations")
            .update({
                "mode_id": mode_id,
                })
            .eq("id", conversation_id)
            .execute()
        )

    def UpdateSummary(self, conversation_id: int, summary: str, timestamp: str):
        if self.database_url:
            self._execute(
                """
                UPDATE conversations
                SET summary = %s, summarized_at = %s, updated_at = now()
                WHERE id = %s
                """,
                (summary, timestamp, conversation_id),
            )
            return

        assert self.client
        _ = (
            self.client
            .table("conversations")
            .update({
                "summary": summary,
                "summarized_at": timestamp,
                })
            .eq("id", conversation_id)
            .execute()
        )

    def UpdateTitle(self, conversation_id: int, title: str):
        if self.database_url:
            self._execute(
                """
                UPDATE conversations
                SET title = %s, updated_at = now()
                WHERE id = %s
                """,
                (title, conversation_id),
            )
            return

        assert self.client
        _ = (
            self.client
            .table("conversations")
            .update({
                "title": title,
                })
            .eq("id", conversation_id)
            .execute()
        )

    def HasTitle(self, conversation_id: int) -> bool:
        if self.database_url:
            row = self._execute_one(
                "SELECT title FROM conversations WHERE id = %s",
                (conversation_id,),
            )
            title = row["title"] if row else None
        else:
            assert self.client
            title = (
                self.client
                .table("conversations")
                .select("title")
                .eq("id", conversation_id)
                .execute()
            ).data[0]["title"]

        if not title or title == "":
            return False
        return True
